## Basic Configuration

baseurl = "https://nu11p01n73R.github.io/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "docs"

author = "Johny James"
title = "Johny James"

theme = "hugo-goa"

## Hugo Built-in Features
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Johny James"
intro = "Stuck In CLI"
description = "Senior Software Engineer @CouponDunia<br/>Trying to build the next big thing"
authorimage = "arch_logo.png"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Johny James Personal Blog"
keywords = "blog,programing,python,go,software,engineering"

## Social Accounts
[params.social]
github = "nu11p01n73R"
linkedin = "johnyjames"
twitter = "nu11p01n73R"
stackoverflow = "3150943/nu11p01n73r"

## Extras
[params.extra]
copyright = "© 2017. Johny James"
poweredby = true
hightlightjs = true

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    url = "https://segmentation-fault.herokuapp.com"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
